name: Build Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LOGSIGHT_LIB_VERSION: v1.3.0
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install "git+https://${INPUT_GITHUB_TOKEN}@github.com/aiops/logsight.git@$LOGSIGHT_LIB_VERSION"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          py.test --junitxml test-report.xml --cov-report xml:coverage-report.xml --cov=logsight_pipeline tests/
